<?php

return [
    'player' => [
        'qq' => [
            'name' => '腾讯视频',
            'tip' => '在线播放',
            'sort' => '999',
            'url' => 'https://v.qq.com',
            'des' => '不负好时光',
            'ps' => '1',
        ],
        'youku' => [
            'name' => '优酷视频',
            'tip' => '在线播放',
            'sort' => '998',
            'url' => 'https://www.youku.com',
            'des' => '这世界很酷',
            'ps' => '1',
        ],
        'qiyi' => [
            'name' => '爱奇艺视频',
            'tip' => '在线播放',
            'sort' => '997',
            'url' => 'https://www.iqiyi.com',
            'des' => '悦享品质',
            'ps' => '1',
        ],
        'sohu' => [
            'name' => '搜狐视频',
            'tip' => '在线播放',
            'sort' => '996',
            'url' => 'https://tv.sohu.com',
            'des' => '看电视剧，更得在搜狐视频',
            'ps' => '1',
        ],
        'letv' => [
            'name' => '乐视视频',
            'tip' => '在线播放',
            'sort' => '995',
            'url' => 'http://www.le.com',
            'des' => '要有你的看法',
            'ps' => '1',
        ],
        'le' => [
            'name' => '乐视视频',
            'tip' => '在线播放',
            'sort' => '995',
            'url' => 'http://www.le.com',
            'des' => '要有你的看法',
            'ps' => '1',
        ],
        'migu' => [
            'name' => '咪咕视频',
            'tip' => '在线播放',
            'sort' => '994',
            'url' => 'https://www.migu.cn',
            'des' => '让今天更有趣',
            'ps' => '1',
        ],
        'funshion' => [
            'name' => '风行视频',
            'tip' => '在线播放',
            'sort' => '993',
            'url' => 'http://www.fun.tv',
            'des' => '看最好的电影',
            'ps' => '1',
        ],
        'fun' => [
            'name' => '风行视频',
            'tip' => '在线播放',
            'sort' => '993',
            'url' => 'http://www.fun.tv',
            'des' => '看最好的电影',
            'ps' => '1',
        ],
        'bilibili' => [
            'name' => '哔哩哔哩',
            'tip' => '在线播放',
            'sort' => '992',
            'url' => 'https://www.bilibili.com',
            'des' => '你感兴趣的视频都在B站',
            'ps' => '1',
        ],
        'mgtv' => [
            'name' => '芒果TV',
            'tip' => '在线播放',
            'sort' => '991',
            'url' => 'https://www.mgtv.com',
            'des' => '天生青春',
            'ps' => '1',
        ],
        'pptv' => [
            'name' => 'PP视频',
            'tip' => '在线播放',
            'sort' => '990',
            'url' => 'https://www.pptv.com',
            'des' => '始终和你同一频道',
            'ps' => '1',
        ],
        'wasu' => [
            'name' => '华数视频',
            'tip' => '在线播放',
            'sort' => '989',
            'url' => 'https://www.wasu.cn',
            'des' => '随心看世界',
            'ps' => '1',
        ],
        'xigua' => [
            'name' => '西瓜视频',
            'tip' => '在线播放',
            'url' => 'https://www.ixigua.com',
            'des' => '点亮对生活的好奇心',
            'sort' => '988',
        ],
        'm1905' => [
            'name' => '1905电影',
            'tip' => '在线播放',
            'sort' => '987',
            'url' => 'https://www.1905.com',
            'des' => '高清影院',
            'ps' => '1',
        ],
        'm3u8' => [
            'name' => '在线播放',
            'tip' => '在线播放',
            'sort' => '986',
        ],
        'ckplayer' => [
            'name' => '在线播放',
            'tip' => '在线播放',
            'sort' => '985',
        ],
    ],
    'downer' => [
        'xunlei' => [
            'name' => '迅雷下载',
            'tip' => '在线下载',
            'sort' => '999',
        ],
        'http' => [
            'name' => '普通下载',
            'tip' => '在线下载',
            'sort' => '998',
        ],
        'ed2k' => [
            'name' => '电驴下载',
            'tip' => '在线下载',
            'sort' => '997',
        ],
        'baidu' => [
            'name' => '百度网盘',
            'tip' => '网盘下载',
            'sort' => '996',
        ],
        'weiyun' => [
            'name' => '微云网盘',
            'tip' => '网盘下载',
            'sort' => '995',
        ],
        'ali' => [
            'name' => '阿里云盘',
            'tip' => '在线下载',
            'sort' => '994',
        ],
        'c189' => [
            'name' => '天翼云盘',
            'tip' => '在线下载',
            'sort' => '993',
        ],
        'magnet' => [
            'name' => '磁力链接',
            'tip' => '在线下载',
            'sort' => '992',
        ],
        'bt' => [
            'name' => 'BT下载',
            'tip' => '在线下载',
            'sort' => '991',
        ],
    ],
];
